apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: gccluster
spec:
  serviceName: clickhouse-headless
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      # no runAsUser needed—UBI + chmod 0777 covers the arbitrary UID
      containers:
        - name: clickhouse
          image: image-registry.openshift-image-registry.svc:5000/gccluster/clickhouse:latest
          ports:
            - name: http
              containerPort: 8123
            - name: native
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
          resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 500m
                memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
        storageClassName: data-2
