apiVersion: v1
kind: Service
metadata:
  name: clickhouse-headless
  namespace: gccluster
spec:
  clusterIP: None
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
    - name: native
      port: 9000
